### ISSUE TITLE
" No configuration setting found for key 'output_relation' "

### ISSUE THREAD

**Issue by kyubumlee** [edoughty/deepdive_genegene_app#1]
I installed Deepdive without any problems and it works fine.
However when I try to run "run.sh", it returns this kind of error msg.
`error com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'output_relation'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'output_relation'`
Is there anyone who has the same problem?

> [info] Running org.deepdive.Main -c /home/kyubum/deepdive/app/deepdive_genegene_app/application.conf
> 22:34:03.346 [][][Slf4jLogger] INFO  Slf4jLogger started
> 22:34:03.357 [run-main-0][EventStream(akka://deepdive)][EventStream] DEBUG logger log1-Slf4jLogger started
> 22:34:03.359 [run-main-0][EventStream(akka://deepdive)][EventStream] DEBUG Default Loggers started
> 22:34:03.363 [run-main-0][Main$(akka://deepdive)][Main$] INFO  Running pipeline with configuration from /home/kyubum/deepdive/app/deepdive_genegene_app/application.conf
> 22:34:03.374 [run-main-0][DeepDive$(akka://deepdive)][DeepDive$] INFO  outputDir=/home/kyubum/deepdive/out/2016-02-10T223402
> [error](run-main-0) com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'output_relation'
> com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'output_relation'
>     at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
>     at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
>     at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
>     at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
>     at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
>     at org.deepdive.settings.SettingsParser$$anonfun$20.apply(SettingsParser.scala:52)
>     at org.deepdive.settings.SettingsParser$$anonfun$20.apply(SettingsParser.scala:50)
>     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
>     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
>     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
>     at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
>     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
>     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
>     at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
>     at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:45)
>     at scala.collection.SetLike$class.map(SetLike.scala:93)
>     at scala.collection.mutable.AbstractSet.map(Set.scala:45)
>     at org.deepdive.settings.SettingsParser$.loadExtractionSettings(SettingsParser.scala:50)
>     at org.deepdive.settings.SettingsParser$.loadFromConfig(SettingsParser.scala:14)
>     at org.deepdive.settings.Settings$.loadFromConfig(Settings.scala:9)
>     at org.deepdive.DeepDive$.run(DeepDive.scala:33)
>     at org.deepdive.Main$delayedInit$body.apply(Main.scala:35)
>     at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
>     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
>     at scala.App$$anonfun$main$1.apply(App.scala:71)
>     at scala.App$$anonfun$main$1.apply(App.scala:71)
>     at scala.collection.immutable.List.foreach(List.scala:318)
>     at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
>     at scala.App$class.main(App.scala:71)
>     at org.deepdive.Main$.main(Main.scala:10)
>     at org.deepdive.Main.main(Main.scala)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
> [trace] Stack trace suppressed: run last compile:run for the full output.

**Comment by edoughty** [comment]
Can you pull changes to the repository and test with the recent changes to the config file? Also, due to an unintentional commit, I had to recreate the repository.

Emily

**Comment by kyubumlee** [comment]
I added dummy lines in the 'application.conf' under "ext_cleanup_genegene", like

```
ext_cleanup_genegene {
      ...

      output_relation: "a"

      input: "select 0"

      udf: ""
}
```

and the error message is gone.

Thanks.
